#include "codegen/io/private.h"

void f2c_io_emit_format_program_support(Context *context) {
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED void f2c_format_descriptor_from_instruction("
        "f2c_format_descriptor *descriptor, const f2c_format_instruction *instruction) { "
        "memset(descriptor, 0, sizeof(*descriptor)); descriptor->code[0] = "
        "instruction->code[0]; descriptor->code[1] = instruction->code[1]; descriptor->width "
        "= instruction->width; descriptor->digits = instruction->digits; descriptor->exponent "
        "= instruction->exponent; if (instruction->code[0] == 'D' && "
        "instruction->code[1] == 'T') { descriptor->iotype = instruction->text != NULL ? "
        "instruction->text : \"DT\"; descriptor->iotype_length = instruction->text != NULL ? "
        "instruction->text_length : 2U; descriptor->v_list = instruction->v_list; "
        "descriptor->v_list_count = instruction->v_list_count; } }\n"
        "static inline F2C_UNUSED int f2c_format_next_program(f2c_format_state *state, "
        "f2c_format_descriptor *descriptor) { bool reverted = false; for (;;) { const "
        "f2c_format_instruction *instruction; uint32_t repeat; if (state->program_position >= "
        "state->program_count) { if (state->finishing) return 0; if (reverted) { state->status "
        "= 0; return 0; } reverted = true; f2c_format_record(state); state->program_position = "
        "state->program_reversion; state->depth = 0U; continue; } instruction = "
        "&state->program[state->program_position]; repeat = instruction->repeat != 0U ? "
        "instruction->repeat : 1U; switch (instruction->opcode) { case "
        "F2C_FORMAT_OP_GROUP_BEGIN: if (!f2c_format_push_frame(state, "
        "state->program_position + 1U, repeat, instruction->unlimited)) return 0; "
        "++state->program_position; break; case F2C_FORMAT_OP_GROUP_END: { f2c_format_frame "
        "*frame; if (state->depth == 0U) { state->status = 0; return 0; } frame = "
        "&state->frames[state->depth - 1U]; if (frame->unlimited) { if (!frame->yielded) { "
        "state->status = 0; return 0; } if (state->finishing) return 0; frame->yielded = false; "
        "state->program_position = frame->start; } else if (frame->remaining > 1U) { "
        "--frame->remaining; frame->yielded = false; state->program_position = frame->start; } "
        "else { --state->depth; ++state->program_position; } break; } case F2C_FORMAT_OP_DATA: "
        "f2c_format_descriptor_from_instruction(descriptor, instruction); "
        "f2c_format_mark_yielded(state); ++state->program_position; state->repeated = "
        "*descriptor; state->repeat_remaining = repeat > 1U ? repeat - 1U : 0U; return 1; "
        "case F2C_FORMAT_OP_LITERAL: while (repeat-- != 0U) "
        "f2c_format_literal(state, instruction->text != NULL ? instruction->text : \"\", "
        "instruction->text_length); ++state->program_position; break; case "
        "F2C_FORMAT_OP_RECORD: while (repeat-- != 0U) f2c_format_record(state); "
        "++state->program_position; break; case F2C_FORMAT_OP_COLON: "
        "++state->program_position; if (state->finishing) return 0; break; case "
        "F2C_FORMAT_OP_SPACE: f2c_format_spaces(state, instruction->control > 0 ? "
        "(size_t)instruction->control : 0U); ++state->program_position; break; case "
        "F2C_FORMAT_OP_POSITION: if (instruction->width > 0) f2c_format_position(state, "
        "instruction->control, (size_t)instruction->width); ++state->program_position; break; "
        "case F2C_FORMAT_OP_SCALE: state->scale = instruction->control; "
        "++state->program_position; break; case F2C_FORMAT_OP_SIGN: state->sign_plus = "
        "instruction->control != 0; ++state->program_position; break; case "
        "F2C_FORMAT_OP_BLANK: state->blank_zero = instruction->control != 0; "
        "++state->program_position; break; case F2C_FORMAT_OP_DECIMAL: state->decimal_comma = "
        "instruction->control != 0; ++state->program_position; break; case "
        "F2C_FORMAT_OP_ROUND: state->rounding = instruction->control; "
        "++state->program_position; break; default: state->status = 0; return 0; } if "
        "(state->status == 0 || state->status == EOF) return 0; } }\n");
}
