#include "codegen/io/private.h"

void f2c_io_emit_format_round_support(Context *context) {
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED int f2c_format_decimal_halfway(double value, int precision) { "
        "long double integral; long double power; long double scaled; if (!isfinite(value) || "
        "precision < 0 || precision > 1000000) return 0; power = powl(10.0L, (long double)"
        "precision); if (!isfinite(power)) return 0; scaled = fabsl((long double)value) * power; "
        "if (!isfinite(scaled)) return 0; return modfl(scaled, &integral) == 0.5L; }\n"
        "static inline F2C_UNUSED int f2c_format_rounding_target(const f2c_format_state *state, "
        "double value, int precision) { switch (state->rounding) { case F2C_FORMAT_ROUND_UP: "
        "return FE_UPWARD; case F2C_FORMAT_ROUND_DOWN: return FE_DOWNWARD; case "
        "F2C_FORMAT_ROUND_ZERO: return FE_TOWARDZERO; case F2C_FORMAT_ROUND_NEAREST: return "
        "FE_TONEAREST; case F2C_FORMAT_ROUND_COMPATIBLE: return "
        "f2c_format_decimal_halfway(value, precision) ? (signbit(value) ? FE_DOWNWARD : "
        "FE_UPWARD) : FE_TONEAREST; default: return -1; } }\n"
        "static inline F2C_UNUSED int f2c_format_begin_rounding(f2c_format_state *state, double "
        "value, int precision, int *saved) { int target; *saved = fegetround(); target = "
        "f2c_format_rounding_target(state, value, precision); if (target < 0) return 1; if "
        "(*saved < 0) { state->status = 0; return 0; } if (target == *saved || "
        "fesetround(target) == 0) return 1; state->status = 0; return 0; }\n"
        "static inline F2C_UNUSED void f2c_format_end_rounding(int saved) { if (saved >= 0 && "
        "fegetround() != saved) (void)fesetround(saved); }\n"
        "static inline F2C_UNUSED char *f2c_format_printf_real(f2c_format_state *state, double "
        "value, int precision, char conversion, size_t *length) { char format[8]; char *field; "
        "int needed; int saved; struct lconv *locale; const char *point; char *decimal; size_t "
        "point_length; if (precision < 0 || precision > 1000000 || (conversion != 'f' && "
        "conversion != 'E')) { state->status = 0; return NULL; } (void)snprintf(format, "
        "sizeof(format), state->sign_plus ? \"%%+.*%c\" : \"%%.*%c\", conversion); if "
        "(!f2c_format_begin_rounding(state, value, precision, &saved)) return NULL; needed = "
        "snprintf(NULL, 0U, format, precision, value); f2c_format_end_rounding(saved); if "
        "(needed < 0 || (size_t)needed == SIZE_MAX) { state->status = 0; return NULL; } field = "
        "(char *)malloc((size_t)needed + 1U); if (field == NULL) { state->status = 0; return "
        "NULL; } if (!f2c_format_begin_rounding(state, value, precision, &saved)) { "
        "free(field); return NULL; } (void)snprintf(field, (size_t)needed + 1U, format, "
        "precision, value); f2c_format_end_rounding(saved); *length = (size_t)needed; locale = "
        "localeconv(); point = locale != NULL ? locale->decimal_point : NULL; point_length = "
        "point != NULL ? strlen(point) : 0U; if (point_length != 0U && !(point_length == 1U && "
        "point[0] == '.')) { decimal = strstr(field, point); if (decimal != NULL) { size_t "
        "offset = (size_t)(decimal - field); decimal[0] = '.'; if (point_length > 1U) { "
        "memmove(decimal + 1U, decimal + point_length, *length - offset - point_length + 1U); "
        "*length -= point_length - 1U; } } } return field; }\n");
}
