#include "codegen/io/private.h"

void f2c_io_emit_format_state_support(Context *context) {
    f2c_buffer_append(
        &context->output,
        "typedef enum f2c_format_opcode { F2C_FORMAT_OP_INVALID, "
        "F2C_FORMAT_OP_GROUP_BEGIN, F2C_FORMAT_OP_GROUP_END, F2C_FORMAT_OP_DATA, "
        "F2C_FORMAT_OP_LITERAL, F2C_FORMAT_OP_RECORD, F2C_FORMAT_OP_COLON, "
        "F2C_FORMAT_OP_SPACE, F2C_FORMAT_OP_POSITION, F2C_FORMAT_OP_SCALE, "
        "F2C_FORMAT_OP_SIGN, F2C_FORMAT_OP_BLANK, F2C_FORMAT_OP_DECIMAL, "
        "F2C_FORMAT_OP_ROUND } f2c_format_opcode;\n"
        "typedef struct f2c_format_instruction { f2c_format_opcode opcode; uint32_t repeat; "
        "bool unlimited; int control; char code[3]; int width; int digits; int exponent; "
        "const char *text; size_t text_length; const int32_t *v_list; size_t v_list_count; } "
        "f2c_format_instruction;\n"
        "typedef struct f2c_format_descriptor { char code[3]; int width; int digits; int "
        "exponent; const char *iotype; size_t iotype_length; const int32_t *v_list; "
        "size_t v_list_count; } f2c_format_descriptor;\n"
        "typedef struct f2c_format_frame { size_t start; uint32_t remaining; bool unlimited; "
        "bool yielded; } f2c_format_frame;\n"
        "typedef struct f2c_format_state { FILE *file; const char *text; size_t length; size_t "
        "position; size_t reversion; const f2c_format_instruction *program; size_t "
        "program_count; size_t program_position; size_t program_reversion; size_t depth; "
        "size_t frame_capacity; f2c_format_frame *frames; f2c_format_descriptor repeated; "
        "uint32_t repeat_remaining; char *scratch_iotype; size_t scratch_iotype_length; "
        "size_t scratch_iotype_capacity; int32_t *scratch_v_list; size_t "
        "scratch_v_list_count; size_t scratch_v_list_capacity; int input; int scale; int "
        "sign_plus; int blank_zero; int decimal_comma; int rounding; size_t column; size_t "
        "pending_spaces; long record_start; int status; int finishing; int record_ended; "
        "size_t transferred; } f2c_format_state;\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED int f2c_format_push_frame(f2c_format_state *state, size_t "
        "start, uint32_t remaining, bool unlimited) { f2c_format_frame *replacement; size_t "
        "capacity; if (state->depth == state->frame_capacity) { capacity = "
        "state->frame_capacity == 0U ? 8U : state->frame_capacity * 2U; if (capacity < "
        "state->frame_capacity || capacity > SIZE_MAX / sizeof(*replacement)) { state->status "
        "= 0; return 0; } replacement = (f2c_format_frame *)realloc(state->frames, capacity * "
        "sizeof(*replacement)); if (replacement == NULL) { state->status = 0; return 0; } "
        "state->frames = replacement; state->frame_capacity = capacity; } "
        "state->frames[state->depth].start = start; state->frames[state->depth].remaining = "
        "remaining != 0U ? remaining : 1U; state->frames[state->depth].unlimited = unlimited; "
        "state->frames[state->depth].yielded = false; ++state->depth; return 1; }\n"
        "static inline F2C_UNUSED void f2c_format_mark_yielded(f2c_format_state *state) { "
        "size_t index; for (index = 0U; index < state->depth; ++index) "
        "state->frames[index].yielded = true; }\n"
        "static inline F2C_UNUSED int f2c_format_reserve_iotype(f2c_format_state *state, "
        "size_t needed) { char *replacement; size_t capacity = state->scratch_iotype_capacity; "
        "if (needed <= capacity) return 1; if (capacity == 0U) capacity = 16U; while (capacity "
        "< needed) { if (capacity > SIZE_MAX / 2U) { capacity = needed; break; } capacity *= "
        "2U; } replacement = (char *)realloc(state->scratch_iotype, capacity); if "
        "(replacement == NULL) { state->status = 0; return 0; } state->scratch_iotype = "
        "replacement; state->scratch_iotype_capacity = capacity; return 1; }\n"
        "static inline F2C_UNUSED int f2c_format_reset_iotype(f2c_format_state *state) { if "
        "(!f2c_format_reserve_iotype(state, 3U)) return 0; state->scratch_iotype[0] = 'D'; "
        "state->scratch_iotype[1] = 'T'; state->scratch_iotype[2] = '\\0'; "
        "state->scratch_iotype_length = 2U; return 1; }\n"
        "static inline F2C_UNUSED int f2c_format_append_iotype(f2c_format_state *state, char "
        "value) { size_t needed; if (state->scratch_iotype_length > SIZE_MAX - 2U) { "
        "state->status = 0; return 0; } needed = state->scratch_iotype_length + 2U; if "
        "(!f2c_format_reserve_iotype(state, needed)) return 0; "
        "state->scratch_iotype[state->scratch_iotype_length++] = value; "
        "state->scratch_iotype[state->scratch_iotype_length] = '\\0'; return 1; }\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED int f2c_format_append_v_list(f2c_format_state *state, "
        "int32_t value) { int32_t *replacement; size_t capacity; if "
        "(state->scratch_v_list_count == state->scratch_v_list_capacity) { capacity = "
        "state->scratch_v_list_capacity == 0U ? 8U : state->scratch_v_list_capacity * 2U; if "
        "(capacity < state->scratch_v_list_capacity || capacity > SIZE_MAX / "
        "sizeof(*replacement)) { state->status = 0; return 0; } replacement = (int32_t "
        "*)realloc(state->scratch_v_list, capacity * sizeof(*replacement)); if (replacement == "
        "NULL) { state->status = 0; return 0; } state->scratch_v_list = replacement; "
        "state->scratch_v_list_capacity = capacity; } "
        "state->scratch_v_list[state->scratch_v_list_count++] = value; return 1; }\n"
        "static inline F2C_UNUSED void f2c_format_initialize_common(f2c_format_state *state, "
        "FILE *file, bool input) { memset(state, 0, sizeof(*state)); state->file = file; "
        "state->input = input ? 1 : 0; state->column = 1U; state->status = file != NULL ? 1 : "
        "0; state->record_start = file != NULL ? ftell(file) : -1L; }\n"
        "static inline F2C_UNUSED void f2c_format_initialize(f2c_format_state *state, FILE "
        "*file, const char *text, size_t length, bool input) { size_t position = 0U; "
        "f2c_format_initialize_common(state, file, input); if (text == NULL && length != 0U) { "
        "state->status = 0; return; } state->text = text != NULL ? text : \"\"; state->length "
        "= length; while (position < length && isspace((unsigned char)state->text[position])) "
        "++position; if (position < length && state->text[position] == '(') ++position; "
        "state->position = position; state->reversion = position; (void)f2c_format_push_frame("
        "state, position, 1U, false); }\n"
        "static inline F2C_UNUSED void f2c_format_initialize_program(f2c_format_state *state, "
        "FILE *file, const f2c_format_instruction *program, size_t count, bool input) { "
        "f2c_format_initialize_common(state, file, input); if "
        "(program == NULL || count == 0U) { state->status = 0; return; } state->program = "
        "program; "
        "state->program_count = count; state->program_reversion = 0U; }\n"
        "static inline F2C_UNUSED void f2c_format_dispose(f2c_format_state *state) { "
        "free(state->frames); state->frames = NULL; state->depth = 0U; state->frame_capacity = "
        "0U; free(state->scratch_iotype); state->scratch_iotype = NULL; "
        "state->scratch_iotype_length = 0U; state->scratch_iotype_capacity = 0U; "
        "free(state->scratch_v_list); state->scratch_v_list = NULL; "
        "state->scratch_v_list_count = 0U; state->scratch_v_list_capacity = 0U; }\n");
}
