#include "internal/f2c.h"

void f2c_emit_format_support(Context *context) {
    f2c_buffer_append(
        &context->output,
        "typedef struct f2c_format_descriptor { char code[3]; int width; int digits; int "
        "exponent; char iotype[128]; int32_t v_list[32]; size_t v_list_count; } "
        "f2c_format_descriptor;\n"
        "typedef struct f2c_format_frame { size_t start; unsigned remaining; } "
        "f2c_format_frame;\n"
        "typedef struct f2c_format_state { FILE *file; const char *text; size_t length; size_t "
        "position; size_t reversion; size_t depth; f2c_format_frame frames[32]; "
        "f2c_format_descriptor repeated; unsigned repeat_remaining; int input; int scale; int "
        "sign_plus; int blank_zero; int decimal_comma; size_t column; long record_start; int "
        "status; int finishing; size_t transferred; } f2c_format_state;\n"
        "static inline F2C_UNUSED int f2c_format_peek(const f2c_format_state *state) { return "
        "state->position < state->length ? (unsigned char)state->text[state->position] : 0; }\n"
        "static inline F2C_UNUSED void f2c_format_spaces(f2c_format_state *state, size_t count) "
        "{ while (count-- != 0U) { if (state->input) { if (fgetc(state->file) == EOF) { "
        "state->status = EOF; return; } } else fputc(' ', state->file); ++state->column; } }\n"
        "static inline F2C_UNUSED void f2c_format_record(f2c_format_state *state) { int c; if "
        "(state->input) { do { c = fgetc(state->file); } while (c != '\\n' && c != EOF); if "
        "(c == EOF) state->status = EOF; } else fputc('\\n', state->file); state->column = 1U; "
        "state->record_start = ftell(state->file); }\n"
        "static inline F2C_UNUSED void f2c_format_literal(f2c_format_state *state, const char "
        "*text, size_t length) { size_t i; for (i = 0U; i < length; ++i) { if (state->input) { "
        "int c = fgetc(state->file); if (c == EOF) state->status = EOF; else if (c != "
        "(unsigned char)text[i]) state->status = 0; } else fputc((unsigned char)text[i], "
        "state->file); ++state->column; } }\n"
        "static inline F2C_UNUSED unsigned f2c_format_unsigned(f2c_format_state *state, int "
        "*present) { unsigned value = 0U; *present = 0; while (isdigit(f2c_format_peek(state))) "
        "{ unsigned digit = (unsigned)(f2c_format_peek(state) - '0'); *present = 1; if (value "
        "<= (UINT32_MAX - digit) / 10U) value = value * 10U + digit; ++state->position; } return "
        "value; }\n"
        "static inline F2C_UNUSED void f2c_format_initialize(f2c_format_state *state, FILE "
        "*file, const char *text, size_t length, bool input) { size_t position = 0U; memset(state, "
        "0, sizeof(*state)); state->file = file; state->text = text; state->length = length; "
        "state->input = input ? 1 : 0; state->column = 1U; state->status = 1; "
        "state->record_start = ftell(file); while (position < length && "
        "isspace((unsigned char)text[position])) ++position; if (position < length && "
        "text[position] == '(') ++position; state->position = position; state->reversion = "
        "position; state->depth = 1U; state->frames[0].start = position; "
        "state->frames[0].remaining = 1U; }\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED void f2c_format_position(f2c_format_state *state, int mode, "
        "size_t amount) { size_t target = mode == 0 ? amount : (mode < 0 ? (state->column > "
        "amount ? state->column - amount : 1U) : state->column + amount); if (target > "
        "state->column) { f2c_format_spaces(state, target - state->column); return; } if (target "
        "< state->column && state->record_start >= 0L && fseek(state->file, "
        "state->record_start + (long)(target - 1U), SEEK_SET) == 0) state->column = target; }\n"
        "static inline F2C_UNUSED int f2c_format_next(f2c_format_state *state, "
        "f2c_format_descriptor *descriptor) { unsigned guard = 0U; if "
        "(state->repeat_remaining != 0U) { *descriptor = state->repeated; "
        "--state->repeat_remaining; return 1; } while (guard++ < 100000U) { int c; int has = 0; "
        "int negative = 0; unsigned prefix, repeats; while ((c = f2c_format_peek(state)) == ' ' || "
        "c == "
        "'\\t' || c == ',') ++state->position; c = f2c_format_peek(state); if (c == 0) { "
        "if (state->finishing) return 0; f2c_format_record(state); state->position = "
        "state->reversion; state->depth = 1U; "
        "continue; } if (c == '+' || c == '-') { negative = c == '-'; ++state->position; } "
        "prefix = f2c_format_unsigned(state, &has); c = toupper(f2c_format_peek(state)); if (c "
        "== '*') { if (has || negative) { state->status = 0; return 0; } ++state->position; while "
        "((c = f2c_format_peek(state)) == ' ' || c == '\\t') ++state->position; if (c != '(') "
        "{ state->status = 0; return 0; } prefix = ~0U; has = 1; } if (c == '(') { if "
        "(state->depth < 32U) { state->frames[state->depth].start = "
        "state->position + 1U; state->frames[state->depth].remaining = has && prefix != 0U ? "
        "prefix : 1U; ++state->depth; } ++state->position; continue; } if (c == ')') { if "
        "(state->depth > 1U) { f2c_format_frame *frame = &state->frames[state->depth - 1U]; if "
        "(frame->remaining > 1U) { --frame->remaining; state->position = frame->start; } else { "
        "--state->depth; ++state->position; } } else { if (state->finishing) return 0; "
        "f2c_format_record(state); state->position = state->reversion; } continue; } if (c == "
        "'\\'' || c == '\"') { int "
        "quote = c; char literal[1024]; size_t literal_length = 0U; ++state->position; while "
        "(state->position < state->length) { c = "
        "(unsigned char)state->text[state->position++]; if (c == quote) { if "
        "(f2c_format_peek(state) == quote) { if (literal_length < sizeof(literal)) "
        "literal[literal_length++] = (char)c; "
        "++state->position; continue; } break; } if (literal_length < sizeof(literal)) "
        "literal[literal_length++] = (char)c; "
        "} f2c_format_literal(state, literal, literal_length); continue; }");
    f2c_buffer_append(
        &context->output,
        "if (has && c == 'H') { ++state->position; { size_t "
        "available = state->length - state->position; size_t count = prefix < available ? "
        "prefix : available; f2c_format_literal(state, state->text + state->position, count); "
        "state->position += count; } continue; } if (c == '/') { unsigned count = has && "
        "prefix != 0U ? prefix : 1U; ++state->position; while (count-- != 0U) "
        "f2c_format_record(state); continue; } if (c == ':') { ++state->position; if "
        "(state->finishing) return 0; continue; } "
        "if (c == 'X') { ++state->position; f2c_format_spaces(state, has ? prefix : 1U); "
        "continue; } if (c == 'T') { int mode = 0; ++state->position; c = "
        "toupper(f2c_format_peek(state)); if (c == 'L' || c == 'R') { mode = c == 'L' ? -1 : "
        "1; ++state->position; } prefix = f2c_format_unsigned(state, &has); if (has) "
        "f2c_format_position(state, mode, prefix); continue; } if (c == 'P') { state->scale = "
        "has ? (negative ? -(int)prefix : (int)prefix) : 0; ++state->position; continue; } if "
        "(c == 'S') { ++state->position; c = toupper(f2c_format_peek(state)); if (c == 'P') { "
        "state->sign_plus = 1; ++state->position; } else if (c == 'S') { state->sign_plus = 0; "
        "++state->position; } continue; } if (c == 'B' && "
        "(toupper((unsigned char)state->text[state->position + (state->position + 1U < "
        "state->length ? 1U : 0U)]) == 'N' || "
        "toupper((unsigned char)state->text[state->position + (state->position + 1U < "
        "state->length ? 1U : 0U)]) == 'Z')) { ++state->position; c = "
        "toupper(f2c_format_peek(state)); state->blank_zero = c == 'Z'; ++state->position; "
        "continue; } if (c == 'R' && state->position + 1U < state->length && "
        "strchr(\"UDZNCP\", toupper((unsigned char)state->text[state->position + 1U])) != NULL) "
        "{ state->position += 2U; continue; } if (c == 'D' && (toupper((unsigned char)"
        "state->text[state->position + (state->position + 1U < state->length ? 1U : 0U)]) == "
        "'C' || toupper((unsigned char)state->text[state->position + (state->position + 1U < "
        "state->length ? 1U : 0U)]) == 'P')) { ++state->position; c = "
        "toupper(f2c_format_peek(state)); state->decimal_comma = c == 'C'; ++state->position; "
        "continue; }");
    f2c_buffer_append(
        &context->output,
        "repeats = has && prefix != 0U ? prefix : 1U; memset(descriptor, 0, "
        "sizeof(*descriptor)); descriptor->code[0] = (char)c; "
        "++state->position; if ((c == 'E' || c == 'D') && (toupper(f2c_format_peek(state)) == "
        "'N' || toupper(f2c_format_peek(state)) == 'S')) descriptor->code[1] = "
        "(char)toupper(state->text[state->position++]); else if (c == 'D' && "
        "toupper(f2c_format_peek(state)) == 'T') descriptor->code[1] = "
        "(char)toupper(state->text[state->position++]); if (descriptor->code[0] == 'D' && "
        "descriptor->code[1] == 'T') { size_t iotype_length = 2U; int quote; "
        "descriptor->iotype[0] = 'D'; descriptor->iotype[1] = 'T'; "
        "descriptor->iotype[2] = '\\0'; while (isspace(f2c_format_peek(state))) "
        "++state->position; quote = f2c_format_peek(state); if (quote == '\\'' || quote == "
        "'\"') { ++state->position; while (state->position < state->length) { int item = "
        "(unsigned char)state->text[state->position++]; if (item == quote) { if "
        "(f2c_format_peek(state) == quote) { ++state->position; } else break; } if "
        "(iotype_length + 1U < sizeof(descriptor->iotype)) descriptor->iotype[iotype_length++] "
        "= (char)item; } descriptor->iotype[iotype_length] = '\\0'; } while "
        "(isspace(f2c_format_peek(state))) ++state->position; if "
        "(f2c_format_peek(state) == '(') { ++state->position; while (state->position < "
        "state->length && descriptor->v_list_count < 32U) { int sign = 1; int present = 0; "
        "unsigned item; while (isspace(f2c_format_peek(state)) || "
        "f2c_format_peek(state) == ',') ++state->position; if (f2c_format_peek(state) == "
        "'-' || f2c_format_peek(state) == '+') { if (f2c_format_peek(state) == '-') sign = "
        "-1; ++state->position; } item = f2c_format_unsigned(state, &present); if (!present) "
        "break; descriptor->v_list[descriptor->v_list_count++] = "
        "(int32_t)(sign * (int)item); while (isspace(f2c_format_peek(state))) "
        "++state->position; if (f2c_format_peek(state) == ')') { ++state->position; break; } "
        "} } } else { prefix = f2c_format_unsigned(state, &has); descriptor->width = has ? "
        "(int)prefix : 0; if (f2c_format_peek(state) == '.') { ++state->position; prefix = "
        "f2c_format_unsigned(state, &has); descriptor->digits = has ? (int)prefix : 0; } if "
        "(toupper(f2c_format_peek(state)) == 'E') { ++state->position; prefix = "
        "f2c_format_unsigned(state, &has); descriptor->exponent = has ? (int)prefix : 0; } } "
        "state->repeated = *descriptor; state->repeat_remaining = "
        "repeats > 1U ? repeats - 1U : 0U; return 1; } state->status = 0; return 0; }\n");

    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED int f2c_format_integer_descriptor(const "
        "f2c_format_descriptor *descriptor) { return descriptor->code[0] == 'I' || "
        "descriptor->code[0] == 'B' || descriptor->code[0] == 'O' || "
        "descriptor->code[0] == 'Z' || descriptor->code[0] == 'G'; }\n"
        "static inline F2C_UNUSED int f2c_format_real_descriptor(const "
        "f2c_format_descriptor *descriptor) { return descriptor->code[0] == 'F' || "
        "descriptor->code[0] == 'E' || descriptor->code[0] == 'D' || "
        "descriptor->code[0] == 'G'; }\n"
        "static inline F2C_UNUSED int f2c_format_logical_descriptor(const "
        "f2c_format_descriptor *descriptor) { return descriptor->code[0] == 'L' || "
        "descriptor->code[0] == 'G'; }\n"
        "static inline F2C_UNUSED int f2c_format_character_descriptor(const "
        "f2c_format_descriptor *descriptor) { return descriptor->code[0] == 'A'; }\n"
        "static inline F2C_UNUSED void f2c_format_field(f2c_format_state *state, const char "
        "*field, size_t length, int width) { size_t target = width > 0 ? (size_t)width : length; "
        "if (length > target) { size_t i; if (state->input) f2c_format_spaces(state, target); "
        "else { for (i = 0U; i < target; ++i) fputc('*', state->file); state->column += target; } "
        "return; } "
        "f2c_format_spaces(state, target - length); if (!state->input) { (void)fwrite(field, 1U, "
        "length, state->file); state->column += length; } }\n"
        "static inline F2C_UNUSED void f2c_format_write_integer(f2c_format_state *state, "
        "int64_t value) { f2c_format_descriptor descriptor; char field[128]; char digits[96]; "
        "size_t length = 0U, minimum; unsigned base = 10U; uint64_t magnitude; int negative; if "
        "(!f2c_format_next(state, &descriptor)) return; if "
        "(!f2c_format_integer_descriptor(&descriptor)) { state->status = 0; return; } if "
        "(descriptor.code[0] == 'B') base = 2U; "
        "else if (descriptor.code[0] == 'O') base = 8U; else if (descriptor.code[0] == 'Z') base "
        "= 16U; negative = value < 0 && base == 10U; magnitude = negative ? "
        "(uint64_t)(-(value + 1)) + 1U : (uint64_t)value; do { unsigned digit = "
        "(unsigned)(magnitude % base); digits[length++] = (char)(digit < 10U ? '0' + digit : 'A' "
        "+ digit - 10U); magnitude /= base; } while (magnitude != 0U && length < "
        "sizeof(digits)); minimum = descriptor.digits > 0 ? (size_t)descriptor.digits : 0U; "
        "while (length < minimum) digits[length++] = '0'; { size_t i = 0U; if (negative) "
        "field[i++] = '-'; else if (state->sign_plus && base == 10U) field[i++] = '+'; while "
        "(length != 0U) field[i++] = digits[--length]; f2c_format_field(state, field, i, "
        "descriptor.width); } }\n"
        "static inline F2C_UNUSED void f2c_format_write_real(f2c_format_state *state, double "
        "value) { f2c_format_descriptor descriptor; char field[256]; int precision; char style; "
        "int length; size_t i; if (!f2c_format_next(state, &descriptor)) return; if "
        "(!f2c_format_real_descriptor(&descriptor)) { state->status = 0; return; } precision = "
        "descriptor.digits > 0 ? descriptor.digits : 6; style = descriptor.code[0] == 'F' ? 'f' "
        ": (descriptor.code[0] == 'G' ? 'G' : 'E'); value *= pow(10.0, (double)state->scale); "
        "if (style == 'f') length = snprintf(field, sizeof(field), state->sign_plus ? \"%+.*f\" : "
        "\"%.*f\", precision, value); else if (style == 'G') length = snprintf(field, "
        "sizeof(field), state->sign_plus ? \"%+.*G\" : \"%.*G\", precision, value); else length "
        "= snprintf(field, sizeof(field), state->sign_plus ? \"%+.*E\" : \"%.*E\", precision, "
        "value); if (length < 0) { state->status = 0; return; } if (descriptor.code[0] == 'D') "
        "for (i = 0U; i < (size_t)length; ++i) if (field[i] == 'E') field[i] = 'D'; if "
        "(state->decimal_comma) for (i = 0U; i < (size_t)length; ++i) if (field[i] == '.') "
        "field[i] = ','; f2c_format_field(state, field, (size_t)length, descriptor.width); }\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED void f2c_format_write_logical(f2c_format_state *state, bool "
        "value) { f2c_format_descriptor descriptor; char field = value ? 'T' : 'F'; if "
        "(f2c_format_next(state, &descriptor)) { if "
        "(!f2c_format_logical_descriptor(&descriptor)) { state->status = 0; return; } "
        "f2c_format_field(state, &field, 1U, descriptor.width); } }\n"
        "static inline F2C_UNUSED void f2c_format_write_character(f2c_format_state *state, "
        "const char *value, size_t length) { f2c_format_descriptor descriptor; size_t width; if "
        "(!f2c_format_next(state, &descriptor)) return; if "
        "(!f2c_format_character_descriptor(&descriptor)) { state->status = 0; return; } width = "
        "descriptor.width > 0 ? "
        "(size_t)descriptor.width : length; if (length > width) length = width; "
        "f2c_format_field(state, value, length, descriptor.width); }\n"
        "static inline F2C_UNUSED int f2c_format_read_field(f2c_format_state *state, char "
        "*field, size_t capacity, int width) { size_t length = 0U; int c; if (capacity == 0U) "
        "return 0; if (width <= 0) return f2c_read_number_token(state->file, field, capacity); "
        "while (length < (size_t)width && (c = fgetc(state->file)) != EOF && c != '\\n' && c "
        "!= '\\r') { if (length + 1U < capacity) field[length] = (char)c; ++length; } if "
        "(length == 0U && feof(state->file)) return EOF; if (length >= capacity) length = "
        "capacity - 1U; field[length] = '\\0'; state->transferred += length; state->column += "
        "(size_t)width; if (c == '\\n' || c == '\\r') state->status = -2; return 1; }\n"
        "static inline F2C_UNUSED void f2c_format_normalize_number(f2c_format_state *state, "
        "char *field) { size_t read = 0U, write = 0U; while (field[read] != '\\0') { char c = "
        "field[read++]; if (c == ' ') { if (state->blank_zero) c = '0'; else continue; } if (c "
        "== 'd' || c == 'D') c = 'e'; if (state->decimal_comma && c == ',') c = '.'; "
        "field[write++] = c; } field[write] = '\\0'; }\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED int f2c_format_read_integer(f2c_format_state *state, int64_t "
        "*value) { f2c_format_descriptor descriptor; char field[256]; int status; int base = 10; "
        "if (!f2c_format_next(state, &descriptor)) return 0; status = "
        "f2c_format_integer_descriptor(&descriptor) ? 1 : 0; if (status == 0) return "
        "state->status = 0; status = "
        "f2c_format_read_field(state, field, sizeof(field), descriptor.width); if (status <= 0) "
        "return state->status = status; f2c_format_normalize_number(state, field); if "
        "(descriptor.code[0] == 'B') base = 2; else if (descriptor.code[0] == 'O') base = 8; "
        "else if (descriptor.code[0] == 'Z') base = 16; *value = (int64_t)strtoll(field, NULL, "
        "base); return 1; }\n"
        "static inline F2C_UNUSED int f2c_format_read_real(f2c_format_state *state, double "
        "*value) { f2c_format_descriptor descriptor; char field[256]; int status; if "
        "(!f2c_format_next(state, &descriptor)) return 0; if "
        "(!f2c_format_real_descriptor(&descriptor)) return state->status = 0; status = "
        "f2c_format_read_field(state, "
        "field, sizeof(field), descriptor.width); if (status <= 0) return state->status = "
        "status; f2c_format_normalize_number(state, field); *value = strtod(field, NULL); if "
        "(strchr(field, '.') == NULL && strchr(field, 'e') == NULL && descriptor.digits > 0) "
        "*value /= pow(10.0, (double)descriptor.digits); *value /= pow(10.0, "
        "(double)state->scale); return 1; }\n"
        "static inline F2C_UNUSED int f2c_format_read_logical(f2c_format_state *state, bool "
        "*value) { f2c_format_descriptor descriptor; char field[64]; int status; size_t i; if "
        "(!f2c_format_next(state, &descriptor)) return 0; if "
        "(!f2c_format_logical_descriptor(&descriptor)) return state->status = 0; status = "
        "f2c_format_read_field(state, "
        "field, sizeof(field), descriptor.width); if (status <= 0) return state->status = "
        "status; for (i = 0U; field[i] != '\\0' && (field[i] == ' ' || field[i] == '.'); ++i) "
        "{} *value = field[i] == 't' || field[i] == 'T' || field[i] == '1'; return 1; }\n"
        "static inline F2C_UNUSED int f2c_format_read_character(f2c_format_state *state, char "
        "*value, size_t length) { f2c_format_descriptor descriptor; size_t width, field = 0U; "
        "size_t destination; int c = 0; if (!f2c_format_next(state, &descriptor)) return 0; if "
        "(!f2c_format_character_descriptor(&descriptor)) return state->status = 0; width = "
        "descriptor.width > 0 ? (size_t)descriptor.width : length; memset(value, ' ', length); "
        "destination = width > length ? width - length : 0U; while (field < width && (c = "
        "fgetc(state->file)) != EOF && c != '\\n' && c != '\\r') { if (field >= destination && "
        "field - destination < length) value[field - destination] = (char)c; ++field; } if "
        "(field == 0U && c == EOF) return state->status = EOF; state->transferred += field; if "
        "(c == '\\n' || c == '\\r') state->status = -2; state->column += width; return 1; "
        "}\n"
        "static inline F2C_UNUSED void f2c_format_finish(f2c_format_state *state, bool advance) { "
        "f2c_format_descriptor descriptor; if (!advance) return; state->finishing = 1; "
        "(void)f2c_format_next(state, "
        "&descriptor); if (state->column != 1U && f2c_child_io_depth == 0U) "
        "f2c_format_record(state); }\n");
}
