#include "codegen/io/private.h"

void f2c_emit_format_support(Context *context) {
    f2c_io_emit_format_state_support(context);
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED int f2c_format_peek(const f2c_format_state *state) { return "
        "state->position < state->length ? (unsigned char)state->text[state->position] : 0; }\n"
        "static inline F2C_UNUSED void f2c_format_flush_spaces(f2c_format_state *state) { "
        "while (!state->input && state->pending_spaces != 0U) { fputc(' ', state->file); "
        "--state->pending_spaces; } }\n"
        "static inline F2C_UNUSED void f2c_format_spaces(f2c_format_state *state, size_t count) "
        "{ while (count-- != 0U) { if (state->input) { if (fgetc(state->file) == EOF) { "
        "state->status = EOF; return; } } else ++state->pending_spaces; ++state->column; } }\n"
        "static inline F2C_UNUSED void f2c_format_end_input_record(f2c_format_state *state, "
        "int terminator) { if (terminator == '\\r') { int next = fgetc(state->file); if (next "
        "!= '\\n' && next != EOF) (void)ungetc(next, state->file); } state->record_ended = 1; "
        "state->column = 1U; state->record_start = ftell(state->file); }\n"
        "static inline F2C_UNUSED void f2c_format_record(f2c_format_state *state) { int c = 0; "
        "if (state->input) { if (!state->record_ended) { do { c = fgetc(state->file); } while "
        "(c != '\\n' && c != '\\r' && c != EOF); if (c == '\\r') { int next = "
        "fgetc(state->file); if (next != '\\n' && next != EOF) (void)ungetc(next, "
        "state->file); } if (c == EOF) state->status = EOF; } state->record_ended = 0; } else "
        "{ state->pending_spaces = 0U; fputc('\\n', state->file); } state->column = 1U; "
        "state->record_start = "
        "ftell(state->file); }\n"
        "static inline F2C_UNUSED void f2c_format_literal(f2c_format_state *state, const char "
        "*text, size_t length) { size_t i; if (!state->input) f2c_format_flush_spaces(state); "
        "for (i = 0U; i < length; ++i) { if (state->input) { "
        "int c = fgetc(state->file); if (c == EOF) state->status = EOF; else if (c != "
        "(unsigned char)text[i]) state->status = 0; } else fputc((unsigned char)text[i], "
        "state->file); ++state->column; } }\n"
        "static inline F2C_UNUSED uint32_t f2c_format_unsigned(f2c_format_state *state, int "
        "*present) { uint32_t value = 0U; *present = 0; while "
        "(isdigit(f2c_format_peek(state))) { uint32_t digit = "
        "(uint32_t)(f2c_format_peek(state) - '0'); *present = 1; if (value > (UINT32_MAX - "
        "digit) / 10U) state->status = 0; else value = value * 10U + digit; "
        "++state->position; } return value; }\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED void f2c_format_position(f2c_format_state *state, int mode, "
        "size_t amount) { size_t target = mode == 0 ? amount : (mode < 0 ? (state->column > "
        "amount ? state->column - amount : 1U) : state->column + amount); if (target > "
        "state->column) { f2c_format_spaces(state, target - state->column); return; } if (target "
        "< state->column && !state->input && state->pending_spaces >= state->column - target) { "
        "state->pending_spaces -= state->column - target; state->column = target; return; } if "
        "(target < state->column && state->record_start >= 0L && fseek(state->file, "
        "state->record_start + (long)(target - 1U), SEEK_SET) == 0) { state->pending_spaces = 0U; "
        "state->column = target; } }\n");
    f2c_io_emit_format_program_support(context);
    f2c_io_emit_format_text_parser_support(context);
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED int f2c_format_integer_descriptor(const "
        "f2c_format_descriptor *descriptor) { return descriptor->code[0] == 'I' || "
        "descriptor->code[0] == 'B' || descriptor->code[0] == 'O' || "
        "descriptor->code[0] == 'Z' || descriptor->code[0] == 'G'; }\n"
        "static inline F2C_UNUSED int f2c_format_real_descriptor(const "
        "f2c_format_descriptor *descriptor) { return descriptor->code[0] == 'F' || "
        "descriptor->code[0] == 'E' || descriptor->code[0] == 'D' || "
        "descriptor->code[0] == 'G'; }\n"
        "static inline F2C_UNUSED int f2c_format_logical_descriptor(const "
        "f2c_format_descriptor *descriptor) { return descriptor->code[0] == 'L' || "
        "descriptor->code[0] == 'G'; }\n"
        "static inline F2C_UNUSED int f2c_format_character_descriptor(const "
        "f2c_format_descriptor *descriptor) { return descriptor->code[0] == 'A'; }\n"
        "static inline F2C_UNUSED void f2c_format_field(f2c_format_state *state, const char "
        "*field, size_t length, int width) { size_t target = width > 0 ? (size_t)width : length; "
        "if (length > target) { size_t i; if (state->input) f2c_format_spaces(state, target); "
        "else { for (i = 0U; i < target; ++i) fputc('*', state->file); state->column += target; } "
        "return; } "
        "f2c_format_spaces(state, target - length); if (!state->input) { "
        "f2c_format_flush_spaces(state); (void)fwrite(field, 1U, length, state->file); "
        "state->column += length; } }\n"
        "static inline F2C_UNUSED void f2c_format_write_integer(f2c_format_state *state, "
        "int64_t value) { f2c_format_descriptor descriptor; char field[128]; char digits[96]; "
        "size_t length = 0U, minimum; unsigned base = 10U; uint64_t magnitude; int negative; if "
        "(!f2c_format_next(state, &descriptor)) return; if "
        "(!f2c_format_integer_descriptor(&descriptor)) { state->status = 0; return; } if "
        "(descriptor.code[0] == 'B') base = 2U; "
        "else if (descriptor.code[0] == 'O') base = 8U; else if (descriptor.code[0] == 'Z') base "
        "= 16U; negative = value < 0 && base == 10U; magnitude = negative ? "
        "(uint64_t)(-(value + 1)) + 1U : (uint64_t)value; do { unsigned digit = "
        "(unsigned)(magnitude % base); digits[length++] = (char)(digit < 10U ? '0' + digit : 'A' "
        "+ digit - 10U); magnitude /= base; } while (magnitude != 0U && length < "
        "sizeof(digits)); minimum = descriptor.digits > 0 ? (size_t)descriptor.digits : 0U; "
        "while (length < minimum) digits[length++] = '0'; { size_t i = 0U; if (negative) "
        "field[i++] = '-'; else if (state->sign_plus && base == 10U) field[i++] = '+'; while "
        "(length != 0U) field[i++] = digits[--length]; f2c_format_field(state, field, i, "
        "descriptor.width); } }\n"
        "static inline F2C_UNUSED void f2c_format_write_real(f2c_format_state *state, double "
        "value) { f2c_format_descriptor descriptor; char field[256]; int precision; char style; "
        "int length; size_t i; if (!f2c_format_next(state, &descriptor)) return; if "
        "(!f2c_format_real_descriptor(&descriptor)) { state->status = 0; return; } precision = "
        "descriptor.digits > 0 ? descriptor.digits : 6; style = descriptor.code[0] == 'F' ? 'f' "
        ": (descriptor.code[0] == 'G' ? 'G' : 'E'); if (style == 'f') value *= "
        "pow(10.0, (double)state->scale); "
        "if (style == 'f') length = snprintf(field, sizeof(field), state->sign_plus ? \"%+.*f\" : "
        "\"%.*f\", precision, value); else if (style == 'G') length = snprintf(field, "
        "sizeof(field), state->sign_plus ? \"%+.*G\" : \"%.*G\", precision, value); else length "
        "= snprintf(field, sizeof(field), state->sign_plus ? \"%+.*E\" : \"%.*E\", precision, "
        "value); if (length < 0) { state->status = 0; return; } if (descriptor.code[0] == 'D') "
        "for (i = 0U; i < (size_t)length; ++i) if (field[i] == 'E') field[i] = 'D'; if "
        "(state->decimal_comma) for (i = 0U; i < (size_t)length; ++i) if (field[i] == '.') "
        "field[i] = ','; f2c_format_field(state, field, (size_t)length, descriptor.width); }\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED void f2c_format_write_logical(f2c_format_state *state, bool "
        "value) { f2c_format_descriptor descriptor; char field = value ? 'T' : 'F'; if "
        "(f2c_format_next(state, &descriptor)) { if "
        "(!f2c_format_logical_descriptor(&descriptor)) { state->status = 0; return; } "
        "f2c_format_field(state, &field, 1U, descriptor.width); } }\n"
        "static inline F2C_UNUSED void f2c_format_write_character(f2c_format_state *state, "
        "const char *value, size_t length) { f2c_format_descriptor descriptor; size_t width; if "
        "(!f2c_format_next(state, &descriptor)) return; if "
        "(!f2c_format_character_descriptor(&descriptor)) { state->status = 0; return; } width = "
        "descriptor.width > 0 ? "
        "(size_t)descriptor.width : length; if (length > width) length = width; "
        "f2c_format_field(state, value, length, descriptor.width); }\n"
        "static inline F2C_UNUSED int f2c_format_read_field(f2c_format_state *state, char "
        "*field, size_t capacity, int width) { size_t length = 0U; int c; if (capacity == 0U) "
        "return 0; if (width <= 0) return f2c_read_number_token(state->file, field, capacity); "
        "while (length < (size_t)width && (c = fgetc(state->file)) != EOF && c != '\\n' && c "
        "!= '\\r') { if (length + 1U < capacity) field[length] = (char)c; ++length; } if "
        "(length == 0U && feof(state->file)) return EOF; if (length >= capacity) length = "
        "capacity - 1U; field[length] = '\\0'; state->transferred += length; if (c == '\\n' || "
        "c == '\\r' || c == EOF) { f2c_format_end_input_record(state, c); state->status = -2; "
        "} else state->column += (size_t)width; return 1; }\n"
        "static inline F2C_UNUSED void f2c_format_normalize_number(f2c_format_state *state, "
        "char *field) { size_t read = 0U, write = 0U; while (field[read] != '\\0') { char c = "
        "field[read++]; if (c == ' ') { if (state->blank_zero) c = '0'; else continue; } if (c "
        "== 'd' || c == 'D') c = 'e'; if (state->decimal_comma && c == ',') c = '.'; "
        "field[write++] = c; } field[write] = '\\0'; }\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED int f2c_format_read_integer(f2c_format_state *state, int64_t "
        "*value) { f2c_format_descriptor descriptor; char field[256]; int status; int base = 10; "
        "if (!f2c_format_next(state, &descriptor)) return 0; status = "
        "f2c_format_integer_descriptor(&descriptor) ? 1 : 0; if (status == 0) return "
        "state->status = 0; status = "
        "f2c_format_read_field(state, field, sizeof(field), descriptor.width); if (status <= 0) "
        "return state->status = status; f2c_format_normalize_number(state, field); if "
        "(descriptor.code[0] == 'B') base = 2; else if (descriptor.code[0] == 'O') base = 8; "
        "else if (descriptor.code[0] == 'Z') base = 16; *value = (int64_t)strtoll(field, NULL, "
        "base); return 1; }\n"
        "static inline F2C_UNUSED int f2c_format_read_real(f2c_format_state *state, double "
        "*value) { f2c_format_descriptor descriptor; char field[256]; int status; if "
        "(!f2c_format_next(state, &descriptor)) return 0; if "
        "(!f2c_format_real_descriptor(&descriptor)) return state->status = 0; status = "
        "f2c_format_read_field(state, "
        "field, sizeof(field), descriptor.width); if (status <= 0) return state->status = "
        "status; f2c_format_normalize_number(state, field); *value = strtod(field, NULL); if "
        "(strchr(field, '.') == NULL && strchr(field, 'e') == NULL && strchr(field, 'E') == NULL "
        "&& descriptor.digits > 0) *value /= pow(10.0, (double)descriptor.digits); if "
        "(strchr(field, 'e') == NULL && strchr(field, 'E') == NULL) *value /= pow(10.0, "
        "(double)state->scale); return 1; }\n"
        "static inline F2C_UNUSED int f2c_format_read_logical(f2c_format_state *state, bool "
        "*value) { f2c_format_descriptor descriptor; char field[64]; int status; size_t i; if "
        "(!f2c_format_next(state, &descriptor)) return 0; if "
        "(!f2c_format_logical_descriptor(&descriptor)) return state->status = 0; status = "
        "f2c_format_read_field(state, "
        "field, sizeof(field), descriptor.width); if (status <= 0) return state->status = "
        "status; for (i = 0U; field[i] != '\\0' && (field[i] == ' ' || field[i] == '.'); ++i) "
        "{} *value = field[i] == 't' || field[i] == 'T' || field[i] == '1'; return 1; }\n"
        "static inline F2C_UNUSED int f2c_format_read_character(f2c_format_state *state, char "
        "*value, size_t length) { f2c_format_descriptor descriptor; size_t width, field = 0U; "
        "size_t destination; int c = 0; if (!f2c_format_next(state, &descriptor)) return 0; if "
        "(!f2c_format_character_descriptor(&descriptor)) return state->status = 0; width = "
        "descriptor.width > 0 ? (size_t)descriptor.width : length; memset(value, ' ', length); "
        "destination = width > length ? width - length : 0U; while (field < width && (c = "
        "fgetc(state->file)) != EOF && c != '\\n' && c != '\\r') { if (field >= destination && "
        "field - destination < length) value[field - destination] = (char)c; ++field; } if "
        "(field == 0U && c == EOF) return state->status = EOF; state->transferred += field; if "
        "(c == '\\n' || c == '\\r' || c == EOF) { f2c_format_end_input_record(state, c); "
        "state->status = -2; } else state->column += width; return 1; "
        "}\n"
        "static inline F2C_UNUSED void f2c_format_finish(f2c_format_state *state, bool advance) { "
        "f2c_format_descriptor descriptor; if (advance) { state->finishing = 1; "
        "(void)f2c_format_next(state, &descriptor); if (state->record_ended) "
        "state->record_ended = 0; else if (state->column != 1U && f2c_child_io_depth == 0U) "
        "f2c_format_record(state); if (state->status == -2) state->status = 1; } "
        "f2c_format_dispose(state); }\n");
}
