#include "internal/f2c.h"

void f2c_emit_namelist_support(Context *context) {
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED bool f2c_namelist_name_equal(const char *left, const char "
        "*right) { while (*left != '\\0' && *right != '\\0') { if "
        "(tolower((unsigned char)*left) != tolower((unsigned char)*right)) return false; "
        "++left; ++right; } return *left == '\\0' && *right == '\\0'; }\n"
        "static inline F2C_UNUSED long f2c_namelist_group(FILE *file, long start, const char "
        "*group) { int c; if (start < 0L || fseek(file, start, SEEK_SET) != 0) return -1L; "
        "while ((c = fgetc(file)) != EOF) { if (c == '&' || c == '$') { char name[128]; "
        "size_t length = 0U; do { c = fgetc(file); } while (c != EOF && "
        "isspace((unsigned char)c)); while (c != EOF && (isalnum((unsigned char)c) || c == "
        "'_')) { if (length + 1U < sizeof(name)) name[length++] = (char)c; c = "
        "fgetc(file); } name[length] = '\\0'; if (c != EOF) ungetc(c, file); if "
        "(f2c_namelist_name_equal(name, group)) return ftell(file); } } return -1L; }\n"
        "static inline F2C_UNUSED bool f2c_namelist_member(FILE *file, long group_start, const "
        "char *member) { int c, quote = 0; if (group_start < 0L || fseek(file, group_start, "
        "SEEK_SET) != 0) return false; while ((c = fgetc(file)) != EOF) { if (quote != 0) { "
        "if (c == quote) { int next = fgetc(file); if (next != quote) { quote = 0; if (next "
        "!= EOF) ungetc(next, file); } } continue; } if (c == '\\'' || c == '\"') { quote "
        "= c; continue; } if (c == '/') return false; if (isalpha((unsigned char)c) || c == "
        "'_') { char name[128]; size_t length = 0U; do { if (length + 1U < sizeof(name)) "
        "name[length++] = (char)c; c = fgetc(file); } while (c != EOF && "
        "(isalnum((unsigned char)c) || c == '_' || c == '%' || c == '(' || c == ')' || "
        "c == ',' || c == '+' || c == '-')); name[length] = '\\0'; while (c != "
        "EOF && "
        "isspace((unsigned char)c)) c = fgetc(file); if (c == '=' && "
        "f2c_namelist_name_equal(name, member)) return true; if (c != EOF) ungetc(c, file); } "
        "} return false; }\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED bool f2c_namelist_next_designator(FILE *file, char *name, "
        "size_t capacity) { int c, quote = 0; while ((c = fgetc(file)) != EOF) { if (quote != "
        "0) { if (c == quote) { int next = fgetc(file); if (next != quote) { quote = 0; if "
        "(next != EOF) ungetc(next, file); } } continue; } if (c == '\\'' || c == '\"') { "
        "quote = c; continue; } if (c == '/') return false; if (isalpha((unsigned char)c) || "
        "c == '_') { size_t length = 0U; int parentheses = 0; for (;;) { bool accepted = "
        "isalnum((unsigned char)c) || c == '_' || c == '%'; if (c == '(') { ++parentheses; "
        "accepted = true; } else if (c == ')' && parentheses > 0) { --parentheses; accepted = "
        "true; } else if (parentheses > 0 && (c == ',' || c == '+' || c == '-' || "
        "isspace((unsigned char)c))) accepted = true; if (!accepted) break; if "
        "(!isspace((unsigned char)c) && length + 1U < capacity) name[length++] = (char)c; c = "
        "fgetc(file); if (c == EOF) break; } name[length] = '\\0'; while (c != EOF && "
        "isspace((unsigned char)c)) c = fgetc(file); if (c == '=') return true; if (c != EOF) "
        "ungetc(c, file); } } return false; }\n"
        "static inline F2C_UNUSED bool f2c_namelist_designator_prefix(FILE *file, long "
        "group_start, const char *member) { char name[512]; size_t length; if (group_start < "
        "0L || fseek(file, group_start, SEEK_SET) != 0) return false; length = strlen(member); "
        "while (f2c_namelist_next_designator(file, name, sizeof(name))) { size_t i = 0U; while "
        "(i < length && name[i] != '\\0' && tolower((unsigned char)name[i]) == "
        "tolower((unsigned char)member[i])) ++i; if (i == length && (name[i] == '\\0' || "
        "name[i] == '%' || name[i] == '(')) return true; } return false; }\n"
        "static inline F2C_UNUSED bool f2c_namelist_designator_bounds(FILE *file, long "
        "group_start, const char *member, size_t rank, int64_t *lower, int64_t *upper) { char "
        "name[512]; size_t member_length, dimension; bool found = false; if (rank == 0U || "
        "group_start < 0L || fseek(file, group_start, SEEK_SET) != 0) return false; "
        "member_length = strlen(member); for (dimension = 0U; dimension < rank; ++dimension) { "
        "lower[dimension] = INT64_MAX; upper[dimension] = INT64_MIN; } while "
        "(f2c_namelist_next_designator(file, name, sizeof(name))) { const char *cursor; char "
        "*end = NULL; size_t i = 0U; while (i < member_length && name[i] != '\\0' && "
        "tolower((unsigned char)name[i]) == tolower((unsigned char)member[i])) ++i; if (i != "
        "member_length || name[i] != '(') continue; cursor = name + i + 1U; for (dimension = "
        "0U; dimension < rank; ++dimension) { int64_t index = (int64_t)strtoll(cursor, &end, "
        "10); if (end == cursor || (dimension + 1U < rank ? *end != ',' : *end != ')')) "
        "break; if (index < lower[dimension]) lower[dimension] = index; if (index > "
        "upper[dimension]) upper[dimension] = index; cursor = end + 1; } if (dimension == rank "
        "&& (*cursor == '\\0' || *cursor == '%')) found = true; } return found; }\n"
        "static inline F2C_UNUSED size_t f2c_namelist_designator_character_length(FILE *file, "
        "long group_start, const char *member) { char name[512]; size_t member_length, maximum "
        "= 0U; if (group_start < 0L || fseek(file, group_start, SEEK_SET) != 0) return 0U; "
        "member_length = strlen(member); while (f2c_namelist_next_designator(file, name, "
        "sizeof(name))) { size_t i = 0U, length = 0U; int c; while (i < member_length && "
        "name[i] != '\\0' && tolower((unsigned char)name[i]) == "
        "tolower((unsigned char)member[i])) ++i; if (i != member_length || (name[i] != "
        "'\\0' && name[i] != '(')) continue; do { c = fgetc(file); } while (c != EOF && "
        "isspace((unsigned char)c)); if (c == '\\'' || c == '\"') { int quote = c; while "
        "((c = fgetc(file)) != EOF) { if (c == quote) { int next = fgetc(file); if (next != "
        "quote) { if (next != EOF) ungetc(next, file); break; } } ++length; } } else { while (c "
        "!= EOF && c != ',' && c != '/' && !isspace((unsigned char)c)) { ++length; c = "
        "fgetc(file); } if (c == '/') ungetc(c, file); } if (length > maximum) maximum = "
        "length; } return maximum; }\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED void f2c_namelist_end(FILE *file, long group_start) { int c, "
        "quote = 0; if (group_start < 0L || fseek(file, group_start, SEEK_SET) != 0) return; "
        "while ((c = fgetc(file)) != EOF) { if (quote != 0) { if (c == quote) { int next = "
        "fgetc(file); if (next != quote) { quote = 0; if (next != EOF) ungetc(next, file); } } "
        "continue; } if (c == '\\'' || c == '\"') quote = c; else if (c == '/') break; } }\n"
        "static inline F2C_UNUSED void f2c_namelist_write_character(FILE *file, const char "
        "*value, size_t length) { size_t i; fputc('\\'', file); for (i = 0U; i < length; ++i) "
        "{ fputc((unsigned char)value[i], file); if (value[i] == '\\'') fputc('\\'', file); "
        "} fputc('\\'', file); }\n");
}
