#ifndef F2C_IR_INTRINSIC_H
#define F2C_IR_INTRINSIC_H

typedef enum F2cIntrinsicId {
    F2C_INTRINSIC_NONE,
    F2C_INTRINSIC_ACHAR,
    F2C_INTRINSIC_ADJUSTL,
    F2C_INTRINSIC_ADJUSTR,
    F2C_INTRINSIC_BIT_SIZE,
    F2C_INTRINSIC_BTEST,
    F2C_INTRINSIC_CHAR,
    F2C_INTRINSIC_IACHAR,
    F2C_INTRINSIC_IAND,
    F2C_INTRINSIC_IBCLR,
    F2C_INTRINSIC_IBITS,
    F2C_INTRINSIC_IBSET,
    F2C_INTRINSIC_ICHAR,
    F2C_INTRINSIC_IEOR,
    F2C_INTRINSIC_INDEX,
    F2C_INTRINSIC_IOR,
    F2C_INTRINSIC_ISHFT,
    F2C_INTRINSIC_ISHFTC,
    F2C_INTRINSIC_LEN,
    F2C_INTRINSIC_LEN_TRIM,
    F2C_INTRINSIC_NOT,
    F2C_INTRINSIC_MVBITS,
    F2C_INTRINSIC_REPEAT,
    F2C_INTRINSIC_SCAN,
    F2C_INTRINSIC_TRIM,
    F2C_INTRINSIC_VERIFY
} F2cIntrinsicId;

#endif
