#include "internal/f2c.h"

void f2c_emit_namelist_transaction_support(Context *context) {
    f2c_buffer_append(
        &context->output,
        "typedef void (*f2c_namelist_rebind_fn)(void *, const void *, size_t, size_t);\n"
        "typedef void (*f2c_namelist_commit_fn)(void *, const void *, size_t, size_t);\n"
        "typedef void (*f2c_namelist_destroy_fn)(void *, size_t, size_t);\n"
        "typedef struct f2c_namelist_mapping { const void *original; void *stage; } "
        "f2c_namelist_mapping;\n"
        "typedef struct f2c_namelist_allocation { void *original; void *stage; size_t count; "
        "size_t element_size, rank; f2c_namelist_rebind_fn rebind; f2c_namelist_commit_fn commit; "
        "f2c_namelist_destroy_fn destroy; } f2c_namelist_allocation;\n"
        "typedef struct f2c_namelist_transaction { f2c_namelist_mapping *mappings; size_t "
        "mapping_count, mapping_capacity; f2c_namelist_allocation *allocations; size_t "
        "allocation_count, allocation_capacity; } f2c_namelist_transaction;\n"
        "static inline F2C_UNUSED void f2c_namelist_transaction_initialize("
        "f2c_namelist_transaction *transaction) { memset(transaction, 0, "
        "sizeof(*transaction)); }\n"
        "static inline F2C_UNUSED void *f2c_namelist_transaction_find("
        "const f2c_namelist_transaction *transaction, const void *original) { size_t i; if "
        "(original == NULL) return NULL; for (i = 0U; i < transaction->mapping_count; ++i) "
        "if (transaction->mappings[i].original == original) return "
        "transaction->mappings[i].stage; return NULL; }\n"
        "static inline F2C_UNUSED bool f2c_namelist_transaction_bind("
        "f2c_namelist_transaction *transaction, const void *original, void *stage) { size_t i, "
        "capacity; f2c_namelist_mapping *replacement; if (original == NULL || stage == NULL) "
        "return original == NULL && stage == NULL; for (i = 0U; i < transaction->mapping_count; "
        "++i) if (transaction->mappings[i].original == original) return "
        "transaction->mappings[i].stage == stage; if (transaction->mapping_count == "
        "transaction->mapping_capacity) { capacity = transaction->mapping_capacity == 0U ? 8U "
        ": transaction->mapping_capacity * 2U; if (capacity < transaction->mapping_capacity || "
        "capacity > SIZE_MAX / sizeof(*replacement)) return false; replacement = "
        "(f2c_namelist_mapping *)realloc(transaction->mappings, capacity * "
        "sizeof(*replacement)); if (replacement == NULL) return false; transaction->mappings = "
        "replacement; transaction->mapping_capacity = capacity; } "
        "transaction->mappings[transaction->mapping_count++] = (f2c_namelist_mapping){"
        "original, stage}; return true; }\n");
    f2c_buffer_append(
        &context->output,
        "static inline F2C_UNUSED bool f2c_namelist_transaction_own("
        "f2c_namelist_transaction *transaction, void *original, void *stage, size_t count, "
        "size_t element_size, size_t rank, f2c_namelist_rebind_fn rebind, "
        "f2c_namelist_commit_fn commit, "
        "f2c_namelist_destroy_fn destroy) { size_t capacity; f2c_namelist_allocation "
        "*replacement; if (original == NULL || stage == NULL || element_size == 0U || "
        "(count != 0U && count > SIZE_MAX / element_size)) return false; if "
        "(transaction->allocation_count == transaction->allocation_capacity) { capacity = "
        "transaction->allocation_capacity == 0U ? 8U : transaction->allocation_capacity * 2U; "
        "if (capacity < transaction->allocation_capacity || capacity > SIZE_MAX / "
        "sizeof(*replacement)) return false; replacement = (f2c_namelist_allocation *)realloc("
        "transaction->allocations, capacity * sizeof(*replacement)); if (replacement == NULL) "
        "return false; transaction->allocations = replacement; transaction->allocation_capacity "
        "= capacity; } if (!f2c_namelist_transaction_bind(transaction, original, stage)) "
        "return false; transaction->allocations[transaction->allocation_count++] = "
        "(f2c_namelist_allocation){original, stage, count, element_size, rank, rebind, commit, "
        "destroy}; "
        "return true; }\n"
        "static inline F2C_UNUSED bool f2c_namelist_size_product(size_t left, size_t right, "
        "size_t *result) { if (right != 0U && left > SIZE_MAX / right) return false; *result = "
        "left * right; return true; }\n"
        "static inline F2C_UNUSED void f2c_namelist_transaction_commit("
        "f2c_namelist_transaction *transaction) { size_t i; for (i = 0U; i < "
        "transaction->allocation_count; ++i) { f2c_namelist_allocation *entry = "
        "&transaction->allocations[i]; if (entry->rebind != NULL) entry->rebind(entry->stage, "
        "entry->original, entry->count, entry->rank); } for (i = 0U; i < "
        "transaction->allocation_count; "
        "++i) { f2c_namelist_allocation *entry = &transaction->allocations[i]; if "
        "(entry->commit != NULL) entry->commit(entry->original, entry->stage, entry->count, "
        "entry->rank); else "
        "if (entry->count != 0U) memmove(entry->original, entry->stage, entry->count * "
        "entry->element_size); } }\n"
        "static inline F2C_UNUSED void f2c_namelist_transaction_destroy("
        "f2c_namelist_transaction *transaction) { size_t i = transaction->allocation_count; "
        "while (i != 0U) { f2c_namelist_allocation *entry = &transaction->allocations[--i]; if "
        "(entry->destroy != NULL) entry->destroy(entry->stage, entry->count, entry->rank); "
        "free(entry->stage); "
        "} free(transaction->allocations); free(transaction->mappings); memset(transaction, 0, "
        "sizeof(*transaction)); }\n"
        "static inline F2C_UNUSED int f2c_namelist_read_status(int status) { return status > 0 "
        "? F2C_IO_STATUS_OK : status == EOF ? EOF : F2C_IO_STATUS_RECORD; }\n");
}
